# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3.8'

services:
  hospital-api:
    image: ${REGISTRY-wisdompetmedicine}/hospitalapi:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/WisdomPetMedicine.Hospital.Api/Dockerfile

  hospital-projector:
    image: ${REGISTRY-wisdompetmedicine}/hospitalprojector:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/WisdomPetMedicine.Hospital.Projector/Dockerfile

  pet-api:
    image: ${REGISTRY-wisdompetmedicine}/petapi:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/WisdomPetMedicine.Pet.Api/Dockerfile

  rescue-api:
    image: ${REGISTRY-wisdompetmedicine}/rescueapi:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/WisdomPetMedicine.Rescue.Api/Dockerfile

  rescuequery-api:
    image: ${REGISTRY-wisdompetmedicine}/rescuequeryapi:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/WisdomPetMedicine.RescueQuery.API/Dockerfile
      