# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "5775:5775"
      - "6831:6831"
      - "6832:6832"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    restart: unless-stopped

  cosmosdb:
    container_name: cosmosdb
    mem_limit: 3g
    cpu_count: 2
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    tty: true
    restart: unless-stopped
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - AZURE_COSMOS_EMULATOR_ARGS='/alternativenames=cosmosdb'
      # - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=${IPADDR:-"`ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}' | head -n 1`"}
      #todo: https://github.com/noelbundick/docker-cosmosdb
    ports:
      - "8081:8081"
      - "10250:10250"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"

  sqldb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      - SA_PASSWORD=MyComplexP@ssword!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    restart: unless-stopped

  hospital-api:
    image: ${REGISTRY-local/wisdompetmedicine}/hospital.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/WisdomPetMedicine.Hospital.Api/Dockerfile
    ports:
      - "5100:80"
    environment:
      - AllowedHosts=*
      - ConnectionStrings__Hospital=Data Source=sqldb,1433;Initial Catalog=Hospital;User Id=sa;Password=MyComplexP@ssword!;Encrypt=false;
      - ServiceBus__ConnectionString=${AZSERVICEBUSSECRET:-}
      - ServiceBus__TopicName=pet-transferred-to-hospital
      - ServiceBus__SubscriptionName=pet-transferred-to-hospital
      - COSMOS_ENDPOINT=https://cosmosdb:8081
      - CosmosDb__ConnectionString=AccountEndpoint=https://cosmosdb:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==;
      - CosmosDb__DatabaseId=WisdomPetMedicine
      - CosmosDb__ContainerId=Patients
      - Jaeger__Host=jaeger
      - Jaeger__Port=6831
      
    depends_on:
      - sqldb
      - cosmosdb
      - jaeger
    restart: unless-stopped

  hospital-projector:
    image: ${REGISTRY-local/wisdompetmedicine}/hospital.projector:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/WisdomPetMedicine.Hospital.Projector/Dockerfile
    environment:
      - ConnectionStrings__Hospital=Data Source=sqldb,1433;Initial Catalog=Hospital;User Id=sa;Password=MyComplexP@ssword!;Encrypt=false;
      - CosmosDbConnectionString=AccountEndpoint=https://cosmosdb:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==;
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - COSMOS_ENDPOINT=https://cosmosdb:8081
      - CosmosDb__ConnectionString=AccountEndpoint=https://cosmosdb:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==;
      - CosmosDb__DatabaseId=WisdomPetMedicine
      - CosmosDb__ContainerId=Patients
      - AzureWebJobsStorage=UseDevelopmentStorage=true
    restart: unless-stopped

  pet-api:
    image: ${REGISTRY-local/wisdompetmedicine}/pet.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/WisdomPetMedicine.Pet.Api/Dockerfile
    ports:
      - "5101:80"
    environment:
      - AllowedHosts=*
      - ConnectionStrings__Pet=Data Source=sqldb,1433;Initial Catalog=Pet;User Id=sa;Password=MyComplexP@ssword!;Encrypt=false;
      - ServiceBus__ConnectionString=${AZSERVICEBUSSECRET:-}
      - ServiceBus__Transfer__TopicName=pet-transferred-to-hospital
      - ServiceBus__Transfer__SubscriptionName=pet-transferred-to-hospital
      - ServiceBus__Adoption__TopicName=pet-flagged-for-adoption
      - ServiceBus__Adoption__SubscriptionName=pet-flagged-for-adoption
      - COSMOS_ENDPOINT=https://cosmosdb:8081
      - CosmosDb__ConnectionString=AccountEndpoint=https://cosmosdb:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==;
      - CosmosDb__DatabaseId=WisdomPetMedicine
      - CosmosDb__ContainerId=Patients
      - Jaeger__Host=jaeger
      - Jaeger__Port=6831
    restart: unless-stopped

  rescue-api:
    image: ${REGISTRY-local/wisdompetmedicine}/rescue.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/WisdomPetMedicine.Rescue.Api/Dockerfile
    ports:
      - "5102:80"
    environment:
      - AllowedHosts=*
      - ConnectionStrings__Rescue=Data Source=sqldb,1433;Initial Catalog=Rescue;User Id=sa;Password=MyComplexP@ssword!;Encrypt=false;
      - ServiceBus__ConnectionString=${AZSERVICEBUSSECRET:-}
      - ServiceBus__TopicName=pet-flagged-for-adoption
      - ServiceBus__SubscriptionName=pet-flagged-for-adoption
      - Jaeger__Host=jaeger
      - Jaeger__Port=6831
    restart: unless-stopped

  rescue-queryapi:
    image: ${REGISTRY-local/wisdompetmedicine}/rescue.queryapi:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/WisdomPetMedicine.RescueQuery.API/Dockerfile
    ports:
      - "5103:80"
    environment:
      - AllowedHosts=*
      - ConnectionStrings__Rescue=Data Source=sqldb,1433;Initial Catalog=Rescue;User Id=sa;Password=MyComplexP@ssword!;Encrypt=false;
      - Jaeger__Host=jaeger
      - Jaeger__Port=6831
    restart: unless-stopped
