version: '3.4'

services:
  wisdompetmedicine.hospital.api:
    image: ${DOCKER_REGISTRY-}wisdompetmedicinehospitalapi
    build:
      context: .
      dockerfile: src/WisdomPetMedicine.Hospital.Api/Dockerfile

  wisdompetmedicine.hospital.projector:
    image: ${DOCKER_REGISTRY-}wisdompetmedicinehospitalprojector
    build:
      context: .
      dockerfile: src/WisdomPetMedicine.Hospital.Projector/Dockerfile


  wisdompetmedicine.pet.api:
    image: ${DOCKER_REGISTRY-}wisdompetmedicinepetapi
    build:
      context: .
      dockerfile: src/WisdomPetMedicine.Pet.Api/Dockerfile


  wisdompetmedicine.rescue.api:
    image: ${DOCKER_REGISTRY-}wisdompetmedicinerescueapi
    build:
      context: .
      dockerfile: src/WisdomPetMedicine.Rescue.Api/Dockerfile


  wisdompetmedicine.rescuequery.api:
    image: ${DOCKER_REGISTRY-}wisdompetmedicinerescuequeryapi
    build:
      context: .
      dockerfile: src/WisdomPetMedicine.RescueQuery.API/Dockerfile

